api_platform:
    mapping:
        paths:
            - '%kernel.project_dir%/src/Backend/UserDirectory/Entity'
            - '%kernel.project_dir%/src/Backend/Consumer/Entity'

    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    show_webby: false
    path_segment_name_generator: App\Backend\ApiPlatform\SpecificNameGenerator